CREATE TABLE IF NOT EXISTS ACTIVE_CHAT (
    ID      SERIAL PRIMARY KEY NOT NULL,
    CHAT_ID BIGINT             NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS INCOMES (
    ID      SERIAL PRIMARY KEY NOT NULL,
    CHAT_ID BIGINT             NOT NULL,
    INCOME  NUMERIC(15, 2)     NOT NULL
);

CREATE TABLE IF NOT EXISTS SPEND (
    ID      SERIAL PRIMARY KEY NOT NULL,
    CHAT_ID BIGINT             NOT NULL,
    SPEND   NUMERIC(15, 2)     NOT NULL
);